# .github/workflows/scheduler.yml

# 이 자동화 작업의 이름을 정합니다.
name: Collect Crypto Data Hourly

# 이 작업을 언제 실행할지 정합니다.
on:
  schedule:
    # cron 표현식: 매시 1분에 실행
    - cron: '1 * * * *'
  # (수동 실행을 위한 옵션) GitHub의 Actions 탭에서 직접 실행할 수도 있습니다.
  workflow_dispatch:

# 실행할 작업들을 정의합니다.
jobs:
  collect-data:
    # 이 작업이 돌아갈 가상 서버 환경을 정합니다.
    runs-on: ubuntu-latest

    # 작업 단계들을 순서대로 나열합니다.
    steps:
      # 1. GitHub 저장소의 코드를 가상 서버로 내려받습니다.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 파이썬을 설치합니다. (원하는 버전으로 변경 가능)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. requirements.txt에 있는 라이브러리들을 설치합니다.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 메인 스크립트를 실행합니다.
      - name: Run data collection script
        # GitHub Secrets에 저장한 값들을 환경 변수로 주입합니다.
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: python main.py
